faskApp/urls.py
from django.contrib import admin
from django.urls import path
from faskApp.views import ( 
logouts,Login,
index_empresa,index_administrador,index_trabajador,
TrabajadorList,TrabajadorCreate,TrabajadorUpdate,TrabajadorDelete,
EmpresaList,EmpresaCreate,EmpresaUpdate,EmpresaDelete,perfilEmpresa,
TreaCreate,TreaList,
AdminEmpresaIndex,
mostrarNotificacionEmpresa,eliminarNotificacionEmpresa,
detalle_empresa,

)

app_name = 'faskApp'
urlpatterns = [
    #URL LOGINS ETC
    path('logout/', logouts, name='logout'),
    path("login/", Login.as_view(), name="login"),
    #URLS AMINISTRADOR
    path('administrador/', index_administrador, name='index_administrador'),
    path('administrador/listar_empresa/',  EmpresaList.as_view(),name='listar_empresa'),
    path('administrador/agregar_empresa/',  EmpresaCreate.as_view(),name='agregar_empresa'),
    path('administrador/editar_empresa/<int:pk>/',  EmpresaUpdate.as_view(),name='editar_empresa'),
    path('administrador/eliminar_empresa/<int:pk>/',  EmpresaDelete.as_view(),name='eliminar_empresa'),
    path('administrador/detalle_empresa/<int:id>/', detalle_empresa, name='detalle_empresa'),


    #URLS TRABAJADOR
    path('trabajador/',index_trabajador,name='index_trabajador'),

    # path('trabajador/',TreaList.as_view(),name='index_trabajador'),
    #URL EMPRESA
    path('perfilempresa/',  perfilEmpresa,name='perfil_empresa'),
    path('empresa/',  index_empresa,name='index_empresa'),
    path('empresa/listar_trabajador/',  TrabajadorList.as_view(),name='listar_trabajadores'),
    path('empresa/agregar_trabajador/',  TrabajadorCreate.as_view(),name='agregar_trabajador'),
    path('empresa/editar_trabajador/<int:pk>/',  TrabajadorUpdate.as_view(),name='editar_trabajador'),
    path('empresa/eliminar_trabajador/<int:pk>/',  TrabajadorDelete.as_view(),name='eliminar_trabajador'),
    path('empresa/crear_tarea/', TreaCreate.as_view(), name='crear_tarea'),
    #notificaciones
    path('empresa/notificacion/show/<int:pk>/',mostrarNotificacionEmpresa , name='show_notif'),
    path('empresa/notificacion/delete/<int:pk>/', eliminarNotificacionEmpresa , name='delete_notif'),
] 

portafolio_v4/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from faskApp import views
from django.conf.urls import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fask/', include('faskApp.urls', namespace='faskApp')),
    path('',views.home, name='home'),
    path('index1/',views.index, name='home1'),
    path('gg/',views.buscarProducto, name='gg'),
   # path('', include("django.contrib.auth.urls"))
]
handler404 = 'faskApp.views.error_404_view' 

templates/empresa_pages/agregar_trabajador.html
{% extends 'Base/index_empresa.html' %}
{% load static crispy_forms_tags %}
{% block contenido %}
<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  {{ form2|crispy }}
  <button type="submit" class="btn btn-accent m-btn m-btn--custom m-btn--icon m-btn--pill m-btn--air">Guardar</button>
</form>
{% endblock%}

templates/empresa_pages/eliminar_trabajador.html
{% extends 'Base/index_empresa.html' %}
{% load static crispy_forms_tags %}
{% block contenido %}
<div class="col-lg-12">
    <div class="card">
        <div class="card-header">
            <strong>Eliminar</strong>
        </div>
        <div class="card-body card-block">
            <form method="POST"> {% csrf_token %}
                <<div class="alert alert-danger" role="alert">
                    ¿Estas seguro de eliminar <strong>{{ trabajador.user.username }}</strong> de los registros?.
        </div>



    </div>
    <div class="card-footer">
        <button class="btn btn-danger" type="submit">Sí, eliminar</button>
        <a class="btn btn-default" href="{% url 'faskApp:listar_trabajadores' %}">Cancelar</a>
        </form>
    </div>
</div>
</div>
{% endblock %}

templates/empresa_pages/index.html
{% extends 'base/index_empresa.html' %}


<!-- si sacas el contenido se mostrara la pagina por defecto del demo -->
{% block contenido %}




<li class="nav-item mx

	<!--begin:: Widgets/Stats-->
							<div class=" m-portlet ">
								<div class=" m-portlet__body m-portlet__body--no-padding">
	<div class="row m-row--no-padding m-row--col-separator-xl">
		<div class="col-md-12 col-lg-6 col-xl-3">
			<!--begin::Total Profit-->
			<div class="m-widget24">
				<div class="m-widget24__item">
					<h4 class="m-widget24__title">
						Trabajadores
					</h4>
					<br>
					<span class="m-widget24__desc">
						All Customs Value
					</span>
					<span class="m-widget24__stats m--font-brand">
						$17,800
					</span>
					<div class="m--space-10"></div>
					<div class="progress m-progress--sm">
						<div class="progress-bar m--bg-brand" role="progressbar" style="width: 78%;" aria-valuenow="50"
							aria-valuemin="0" aria-valuemax="100"></div>
					</div>
					<span class="m-widget24__change">
						Change
					</span>
					<span class="m-widget24__number">
						78%
					</span>
				</div>
			</div>
			<!--end::Total Profit-->
		</div>
		<div class="col-md-12 col-lg-6 col-xl-3">
			<!--begin::New Feedbacks-->
			<div class="m-widget24">
				<div class="m-widget24__item">
					<h4 class="m-widget24__title">
						Tareas completas
					</h4>
					<br>
					<span class="m-widget24__desc">
						Customer Review
					</span>
					<span class="m-widget24__stats m--font-info">
						1349
					</span>
					<div class="m--space-10"></div>
					<div class="progress m-progress--sm">
						<div class="progress-bar m--bg-info" role="progressbar" style="width: 84%;" aria-valuenow="50"
							aria-valuemin="0" aria-valuemax="100"></div>
					</div>
					<span class="m-widget24__change">
						Change
					</span>
					<span class="m-widget24__number">
						84%
					</span>
				</div>
			</div>
			<!--end::New Feedbacks-->
		</div>
		<div class="col-md-12 col-lg-6 col-xl-3">
			<!--begin::New Orders-->
			<div class="m-widget24">
				<div class="m-widget24__item">
					<h4 class="m-widget24__title">
						Tareas incompletas
					</h4>
					<br>
					<span class="m-widget24__desc">
						Fresh Order Amount
					</span>
					<span class="m-widget24__stats m--font-danger">
						567
					</span>
					<div class="m--space-10"></div>
					<div class="progress m-progress--sm">
						<div class="progress-bar m--bg-danger" role="progressbar" style="width: 69%;" aria-valuenow="50"
							aria-valuemin="0" aria-valuemax="100"></div>
					</div>
					<span class="m-widget24__change">
						Change
					</span>
					<span class="m-widget24__number">
						69%
					</span>
				</div>
			</div>
			<!--end::New Orders-->
		</div>
		<div class="col-md-12 col-lg-6 col-xl-3">
			<!--begin::New Users-->
			<div class="m-widget24">
				<div class="m-widget24__item">
					<h4 class="m-widget24__title">
						Avance Global
					</h4>
					<br>
					<span class="m-widget24__desc">
						Joined New User
					</span>
					<span class="m-widget24__stats m--font-success">
						276
					</span>
					<div class="m--space-10"></div>
					<div class="progress m-progress--sm">
						<div class="progress-bar m--bg-success" role="progressbar" style="width: 90%;"
							aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
					</div>
					<span class="m-widget24__change">
						Change
					</span>
					<span class="m-widget24__number">
						90%
					</span>
				</div>
			</div>
			<!--end::New Users-->
		</div>
	</div>
	</div>
	</div>

	{% endblock contenido %}

templates/empresa_pages/lista_trabajadores.html
{% extends 'Base/index_empresa.html' %}
{% load static crispy_forms_tags %}

{% block contenido %}

<table class="table table-bordered">
	<thead>
		<tr>
			<td>No. Solicitud</td>
			<td>Username</td>
			<td>nombre</td>
			<td>Ap</td>
			<td>Emprsa id</td>
			<td>trabajador empresa id</td>
			<td>Empresa</td>
			<td>Acciones</td>
		</tr>

	</thead>
	<tbody>

		{% if object_list %}
		{% for trabajador in object_list %}
		{% if trabajador.empresa.user_id == request.user.id %}
		<tr>
			<td>{{trabajador.id }}</td>
			<td>{{trabajador.user.username }}</td>
			<td>{{trabajador.apellidoP}} </td>
			<td>{{trabajador.user.email}} </td>
			<td>{{trabajador.empresa.user_id}} </td>
			<td>{{trabajador.empresa_id}} gg </td>
			<td>{{trabajador.empresa.nombre}} </td>


			<td>
				<a class="btn btn-primary" href="{% url "faskApp:editar_trabajador"  trabajador.id %}">Editar</a>
				<a class="btn btn-danger" href="{% url "faskApp:eliminar_trabajador"  trabajador.id %}">Eliminar</a>
			</td>
		</tr>
		{% endif %}
		{% endfor %}

		{% else %}
		<h1>No hay registros de solicitudes</h1>
		{% endif %}
	</tbody>
</table>

{% endblock%}

templates/empresa_pages/notificacion_empresa.html
{% extends 'base/index_empresa.html' %}


<!-- si sacas el contenido se mostrara la pagina por defecto del demo -->
{% block contenido %}

<h2>{{notificaciones.titulo}}</h2>
<h2>{{notificaciones.comentario}}</h2>
<h2><a href="{% url "faskApp:delete_notif" notificaciones.id %}">Marcar como leido</h2>




{% endblock contenido %}

templates/empresa_pages/perfil_empresa.html
{% extends 'Base/index_empresa.html' %}

{% load crispy_forms_tags %}



{% block contenido %}
<div class="container">

    <h1>Perfil</h1>
    <p>Usuario: {{ user }}</p>
    <p>Nombre: {{ user.first_name }}</p>
    {% if object_list %}
    <p>Apellidos: {{ object_list.nombre }}</p>
    {% endif%}
    <p>Email: {{ user.email }}</p>

    <a class="btn btn-primary" href="{% url "faskApp:editar_empresa"  user.id %}">Editar</a>
</div>

{% endblock %}