faskApp/urls.py
from django.contrib import admin
from django.urls import path
from faskApp.views import ( 
logouts,Login,
index_empresa,index_administrador,index_trabajador,
TrabajadorList,TrabajadorCreate,TrabajadorUpdate,TrabajadorDelete,
EmpresaList,EmpresaCreate,EmpresaUpdate,EmpresaDelete,perfilEmpresa,
TreaCreate,TreaList,
AdminEmpresaIndex,
mostrarNotificacionEmpresa,eliminarNotificacionEmpresa,
detalle_empresa,

)

app_name = 'faskApp'
urlpatterns = [
    #URL LOGINS ETC
    path('logout/', logouts, name='logout'),
    path("login/", Login.as_view(), name="login"),
    #URLS AMINISTRADOR
    path('administrador/', index_administrador, name='index_administrador'),
    path('administrador/listar_empresa/',  EmpresaList.as_view(),name='listar_empresa'),
    path('administrador/agregar_empresa/',  EmpresaCreate.as_view(),name='agregar_empresa'),
    path('administrador/editar_empresa/<int:pk>/',  EmpresaUpdate.as_view(),name='editar_empresa'),
    path('administrador/eliminar_empresa/<int:pk>/',  EmpresaDelete.as_view(),name='eliminar_empresa'),
    path('administrador/detalle_empresa/<int:id>/', detalle_empresa, name='detalle_empresa'),


    #URLS TRABAJADOR
    path('trabajador/',index_trabajador,name='index_trabajador'),

    # path('trabajador/',TreaList.as_view(),name='index_trabajador'),
    #URL EMPRESA
    path('perfilempresa/',  perfilEmpresa,name='perfil_empresa'),
    path('empresa/',  index_empresa,name='index_empresa'),
    path('empresa/listar_trabajador/',  TrabajadorList.as_view(),name='listar_trabajadores'),
    path('empresa/agregar_trabajador/',  TrabajadorCreate.as_view(),name='agregar_trabajador'),
    path('empresa/editar_trabajador/<int:pk>/',  TrabajadorUpdate.as_view(),name='editar_trabajador'),
    path('empresa/eliminar_trabajador/<int:pk>/',  TrabajadorDelete.as_view(),name='eliminar_trabajador'),
    path('empresa/crear_tarea/', TreaCreate.as_view(), name='crear_tarea'),
    #notificaciones
    path('empresa/notificacion/show/<int:pk>/',mostrarNotificacionEmpresa , name='show_notif'),
    path('empresa/notificacion/delete/<int:pk>/', eliminarNotificacionEmpresa , name='delete_notif'),
] 

portafolio_v4/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from faskApp import views
from django.conf.urls import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fask/', include('faskApp.urls', namespace='faskApp')),
    path('',views.home, name='home'),
    path('index1/',views.index, name='home1'),
    path('gg/',views.buscarProducto, name='gg'),
   # path('', include("django.contrib.auth.urls"))
]
handler404 = 'faskApp.views.error_404_view' 

templates/admin_pages/agregar_empresa.html
{% extends 'Base/index_admin.html' %}
{% load static crispy_forms_tags %}
{% block contenido %}
<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  {{ form2|crispy }}

  <button type="submit" class="btn btn-accent m-btn m-btn--custom m-btn--icon m-btn--pill m-btn--air">Guardar</button>
</form>
{% endblock%}

templates/admin_pages/detalle_empresa.html
{% extends 'base/index_admin.html' %}


<!-- si sacas el contenido se mostrara la pagina por defecto del demo -->
{% block contenido %}

{% for row in detalle_empresa %}
{{row}}
{% endfor %}

{% endblock contenido %}

templates/admin_pages/eliminar_empresa.html
{% extends 'Base/index_admin.html' %}
{% load static crispy_forms_tags %}
{% block contenido %}
<div class="col-lg-12">
    <div class="card">
        <div class="card-header">
            <strong>Eliminar</strong>
        </div>
        <div class="card-body card-block">
            <form method="POST"> {% csrf_token %}
                <<div class="alert alert-danger" role="alert">
                    ¿Estas seguro de eliminar <strong>{{ empresa.user.username }}</strong> de los registros?.
        </div>



    </div>
    <div class="card-footer">
        <button class="btn btn-danger" type="submit">Sí, eliminar</button>
        <a class="btn btn-default" href="{% url 'faskApp:listar_empresa' %}">Cancelar</a>
        </form>
    </div>
</div>
</div>
{% endblock %}

templates/admin_pages/index.html
{% extends 'base/index_admin.html' %}


<!-- si sacas el contenido se mostrara la pagina por defecto del demo -->
{% block contenido %}

<h1>Empresas</h1>



<div class="m-content">



	<div class="row justify-content-center justify-content-md-start">
		{% if empresa %}
		{% for empresa in empresa %}
		<div class="col-xl-4">
			<div class="m-portlet  m-portlet--bordered-semi m-portlet--skin-dark m-portlet--full-height ">
				<div class="m-portlet__head">
					<div class="m-portlet__head-caption">
						<div class="m-portlet__head-title">
							<h3 class="m-portlet__head-text">
								{{empresa.nombre}}
							</h3>
						</div>
					</div>
					<div class="m-portlet__head-tools">

						<ul class="m-portlet__nav">
							<li class="m-portlet__nav-item ">
								<a href="{% url "faskApp:editar_empresa"  empresa.id %}"
									class=" btn btn-outline-success btn-sm">
									Editar empresa
								</a>
							</li>
						</ul>

					</div>
				</div>
				<div class="m-portlet__body">
					<!--begin::Widget5-->
					<div class="m-widget4">
						Descripcion

						<div class="m-widget4__item">
							<div class="m-widget4__img m-widget4__img--logo">
								<img src="assets/app/media/img/client-logos/logo3.png" alt="">
							</div>
							<div class="m-widget4__info">
								<span class="m-widget4__title">
									Total trabajadores
								</span>
								<br>
								<span class="m-widget4__sub">
									A Programming Language
								</span>
							</div>
							<span class="m-widget4__ext">
								<span class="m-widget4__number m--font-danger">
									(numero de trabajaodres)
								</span>
							</span>
						</div>
						<div class="m-widget4__item">
							<div class="m-widget4__img m-widget4__img--logo">
								<img src="assets/app/media/img/client-logos/logo1.png" alt="">
							</div>
							<div class="m-widget4__info">
								<span class="m-widget4__title">
									Total tareas
								</span>
								<br>
								<span class="m-widget4__sub">
									A Let's Fly Fast Again Language
								</span>
							</div>
							<span class="m-widget4__ext">
								<span class="m-widget4__number m--font-danger">
									+$300
								</span>
							</span>
						</div>
						<div class="m-widget4__item">
							<div class="m-widget4__img m-widget4__img--logo">
								<img src="assets/app/media/img/client-logos/logo2.png" alt="">
							</div>
							<div class="m-widget4__info">
								<span class="m-widget4__title">
									AirApp
								</span>
								<br>
								<span class="m-widget4__sub">
									Awesome App For Project Management
								</span>
							</div>
							<span class="m-widget4__ext">
								<span class="m-widget4__number m--font-danger">
									+$6700
								</span>
							</span>
						</div>
					</div>



					<div class="m-demo__preview  m-demo__preview--btn">

						<a href="{% url "faskApp:detalle_empresa"  empresa.id %}" class="btn btn-success">
							Editar empresa
						</a>

					</div>





					<!--end::Widget 5-->
				</div>

			</div>

			<!--end:: Widgets/Top Products-->
		</div>
		{% endfor %}

		{% else %}
		<h1>No hay registros de solicitudes</h1>
		{% endif %}
		<div class="col-sm-4 align-self-center">
			<div class="m-section__content ">

				<a href="{% url "faskApp:agregar_empresa"  %}"
					class="btn m-btn--pill btn-primary btn-lg __web-inspector-hide-shortcut__  btn-block"">
														Agregar empresa
													</a>	

    

      </div>
    </div>
    <div class=" col-sm-4">
					--
			</div>

		</div>

	</div>

	{% endblock contenido %}

templates/admin_pages/listar_empresa.html
{% extends 'Base/index_admin.html' %}
{% load static crispy_forms_tags %}

{% block contenido %}

<table class="table table-bordered">
	<thead>
		<tr>
			<td>#</td>
			<td>Nombre empresa</td>
			<td>Rut</td>
			<td>Nombre usuario</td>
			<td>Email</td>
			<td>Telefono</td>
			<td>Acciones</td>
		</tr>

	</thead>
	<tbody>

		{% if object_list %}
		{% for empresa in object_list %}
		<tr>
			<td>{{ forloop.counter  }}</td>
			<td>{{ empresa.nombre }}</td>
			<td>{{ empresa.rut }}</td>
			<td>{{empresa.user.username}} </td>
			<td>{{empresa.user.Email}} </td>
			<td>{{empresa.telefono}} </td>


			<td>
				<a class="btn btn-primary" href="{% url "faskApp:editar_empresa"  empresa.id %}">Editar</a>
				<a class="btn btn-danger" href="{% url "faskApp:eliminar_empresa"  empresa.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}

		{% else %}
		<h1>No hay registros de solicitudes</h1>
		{% endif %}
	</tbody>
</table>

{% endblock%}